package org.greendao.autogen;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.tgithubc.kumao.bean.KeyWord;
import com.tgithubc.kumao.bean.Song;

import org.greendao.autogen.KeyWordDao;
import org.greendao.autogen.SongDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig keyWordDaoConfig;
    private final DaoConfig songDaoConfig;

    private final KeyWordDao keyWordDao;
    private final SongDao songDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        keyWordDaoConfig = daoConfigMap.get(KeyWordDao.class).clone();
        keyWordDaoConfig.initIdentityScope(type);

        songDaoConfig = daoConfigMap.get(SongDao.class).clone();
        songDaoConfig.initIdentityScope(type);

        keyWordDao = new KeyWordDao(keyWordDaoConfig, this);
        songDao = new SongDao(songDaoConfig, this);

        registerDao(KeyWord.class, keyWordDao);
        registerDao(Song.class, songDao);
    }
    
    public void clear() {
        keyWordDaoConfig.clearIdentityScope();
        songDaoConfig.clearIdentityScope();
    }

    public KeyWordDao getKeyWordDao() {
        return keyWordDao;
    }

    public SongDao getSongDao() {
        return songDao;
    }

}
