package org.greendao.autogen;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.tgithubc.kumao.bean.Song;
import com.tgithubc.kumao.bean.KeyWord;

import org.greendao.autogen.SongDao;
import org.greendao.autogen.KeyWordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig songDaoConfig;
    private final DaoConfig keyWordDaoConfig;

    private final SongDao songDao;
    private final KeyWordDao keyWordDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        songDaoConfig = daoConfigMap.get(SongDao.class).clone();
        songDaoConfig.initIdentityScope(type);

        keyWordDaoConfig = daoConfigMap.get(KeyWordDao.class).clone();
        keyWordDaoConfig.initIdentityScope(type);

        songDao = new SongDao(songDaoConfig, this);
        keyWordDao = new KeyWordDao(keyWordDaoConfig, this);

        registerDao(Song.class, songDao);
        registerDao(KeyWord.class, keyWordDao);
    }
    
    public void clear() {
        songDaoConfig.clearIdentityScope();
        keyWordDaoConfig.clearIdentityScope();
    }

    public SongDao getSongDao() {
        return songDao;
    }

    public KeyWordDao getKeyWordDao() {
        return keyWordDao;
    }

}
