package org.greendao.autogen;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.tgithubc.kumao.bean.KeyWord;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "KEY_WORD".
*/
public class KeyWordDao extends AbstractDao<KeyWord, Void> {

    public static final String TABLENAME = "KEY_WORD";

    /**
     * Properties of entity KeyWord.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property KeyWord = new Property(0, String.class, "keyWord", false, "KEY_WORD");
        public final static Property SearchTime = new Property(1, long.class, "searchTime", false, "SEARCH_TIME");
    }


    public KeyWordDao(DaoConfig config) {
        super(config);
    }
    
    public KeyWordDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"KEY_WORD\" (" + //
                "\"KEY_WORD\" TEXT," + // 0: keyWord
                "\"SEARCH_TIME\" INTEGER NOT NULL );"); // 1: searchTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"KEY_WORD\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, KeyWord entity) {
        stmt.clearBindings();
 
        String keyWord = entity.getKeyWord();
        if (keyWord != null) {
            stmt.bindString(1, keyWord);
        }
        stmt.bindLong(2, entity.getSearchTime());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, KeyWord entity) {
        stmt.clearBindings();
 
        String keyWord = entity.getKeyWord();
        if (keyWord != null) {
            stmt.bindString(1, keyWord);
        }
        stmt.bindLong(2, entity.getSearchTime());
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public KeyWord readEntity(Cursor cursor, int offset) {
        KeyWord entity = new KeyWord( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // keyWord
            cursor.getLong(offset + 1) // searchTime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, KeyWord entity, int offset) {
        entity.setKeyWord(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setSearchTime(cursor.getLong(offset + 1));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(KeyWord entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(KeyWord entity) {
        return null;
    }

    @Override
    public boolean hasKey(KeyWord entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
